### ISSUE TITLE
当recursive设置为true的时候， input的dir有子目录时候， 内存爆表了

### ISSUE THREAD

**Issue by cyuxlif** [caixw/apidoc#1]
![image](https://cloud.githubusercontent.com/assets/5780053/14662535/9ecca9a4-06e9-11e6-987e-a6b252788108.png)
当recursive设置为true的时候， input的dir有子目录时候， 内存爆表了

**Comment by caixw** [comment]
@cyuxlif  能给个具体的操作环境和.apidoc.json的内容吗？

**Comment by cyuxlif** [comment]
![image](https://cloud.githubusercontent.com/assets/5780053/14696359/eaf5f13c-07ac-11e6-867e-8a5a94d2bf76.png)
![image](https://cloud.githubusercontent.com/assets/5780053/14696363/fa32b626-07ac-11e6-84a9-6dd98cf8e9d2.png)

**Comment by cyuxlif** [comment]
![image](https://cloud.githubusercontent.com/assets/5780053/14696408/640742ba-07ad-11e6-96e3-6a05ce1b2288.png)

**Comment by cyuxlif** [comment]
看了下源码找到问题所在了，这里注册了一个路由
![image](https://cloud.githubusercontent.com/assets/5780053/14697717/1dc44a1c-07b9-11e6-9a74-84af84a31aea.png)
然后这里匹配出问题了， 陷入死循环了
![image](https://cloud.githubusercontent.com/assets/5780053/14697724/3b5d6ca2-07b9-11e6-9688-57b45af5e7c1.png)
