### ISSUE TITLE
能否增加目录

### ISSUE THREAD

**Issue by hugcoday** [caixw/apidoc#21]
生成后的页面，比较简单，能否像apidocjs一样，带有目录结构；

如果是长文档，找起来比较麻烦，

**Comment by hugcoday** [comment]
大概是这个样子 ：http://apidocjs.com/example/

**Comment by caixw** [comment]
这个版本有可能会对模板进行一些调整，不过优先级不是很高。
如果你在这方面有比较大的需求，可以尝试自定义模板。

**Comment by caixw** [comment]
新版采用动态加载 JSON 的方式
