### ISSUE TITLE
关于  此配置文件的 apidoc 版本号

### ISSUE THREAD

**Issue by hugcoday** [caixw/apidoc#22]
“产生此配置文件的 apidoc 版本号”，存在这个版本号，

难道是为了不兼容的情况，这个不应该向下自动兼容吗？

**Comment by caixw** [comment]
兼容性问题，参考 semver 的规格，大版本号不同，理论上是不会相互兼容的。

兼容性问题主要体现在配置文件以及部分标签的语法。

目前是牌 3.0 alpha 阶段，与 2.x 不兼容，也正式版的 3.x 也有可能不兼容。
