### ISSUE TITLE
没有示例吗，初学，有点懵逼。

### ISSUE THREAD

**Issue by zldafeng** [caixw/apidoc#29]
怎么看看效果，go run main.go ?
# command-line-arguments
.\main.go:33: undefined: logWriter
.\main.go:34: undefined: logWriter
.\main.go:35: undefined: logWriter
.\main.go:131: undefined: loadConfig
.\main.go:202: undefined: config

**Comment by caixw** [comment]
go run main.go 只会以 main.go 单个文件进行编译运行，自然会出错。你可以用以下命令：
```shell
go build
```
或是
```
go install
```
一个将程序编译在当前目录，一个将程序编译在 $GOPATH/bin 目录下。
之后你就可使用 apidoc 运行了。

**Comment by zldafeng** [comment]
方便留个qq 或者微信吗，请教一下

**Comment by caixw** [comment]
额，可以发我邮箱，基本上都在线，xnotepad#gmail.com

**Comment by zldafeng** [comment]
有没有示例。。。。

**Comment by caixw** [comment]
http://apidoc.tools/#usage

http://apidoc.tools/example/doc/index.html
