### ISSUE TITLE
生成的HTML浏览器兼容问题(Google Chrome显示异常)

### ISSUE THREAD

**Issue by hyangit** [caixw/apidoc#34]
![image](https://user-images.githubusercontent.com/13882929/32211639-6d52954a-bde1-11e7-8baa-28c612f1b88a.png)
图中的导航条应该固定在顶部，但是在Google Chrome中会随页面滚动而下移

**Comment by caixw** [comment]
我应该是引用了旧版的 UI 库引起的。
