### ISSUE TITLE
HTML输出方式不能用

### ISSUE THREAD

**Issue by ahlzhang** [caixw/apidoc#37]
为什么要去掉html方式呢？是否可以恢复html的输出方式。

**Comment by caixw** [comment]
功能都还在，只不过现在是通过在 html 页面动态加载 json 数据的方式实现的，不像原来直接保存成一系列的 html 文件。

**Comment by ahlzhang** [comment]
有更详细的文档可以看吗？现在是不知道怎么使用。出来的是一个css和js文件。你现在的文档也没有更新。

**Comment by ahlzhang** [comment]
好吧，我暂时先用之前的版本。

**Comment by ahlzhang** [comment]
如果主分支已经完结，请发版一个正式版本出来。谢谢。

**Comment by caixw** [comment]
输出改为 xml+xslt 的方式展示，html 不再启作用。
