### ISSUE TITLE
代码高亮依赖资源 404

### ISSUE THREAD

**Issue by bruinxs** [caixw/apidoc#41]
资源 https://cdn.bootcss.com/prism/1.5.1/components/ 404，导致代码无法高亮

该资源是否可以改成放在本地，不要请求网络资源

**Comment by caixw** [comment]
如果将所有的第三方资源都打包在可执行文件中，文件本身会变得非常大。
所以目前对这些第三方资源的处理方式就是引用 CDN 上的内容。
如果是在一个无法联网的环境中，的确会 404。
