### ISSUE TITLE
生成doc的时候是否支持例外

### ISSUE THREAD

**Issue by godcong** [caixw/apidoc#42]
生成doc的时候发现
apidoc会把vendor目录也包含进去.
但是vendor都是引用的项目,并非自己的.
有些还会造成语法错误,导致apidoc报错.
是否可以直接在配置文件中添加例外?

**Comment by caixw** [comment]
不能指定例外。但是可以指定多个输入源，可能有点麻烦，但是可以达到相同的效果。

**Comment by godcong** [comment]
谢谢,希望以后的版本可以加上哦
