### ISSUE TITLE
文档不能查看么？运行失败

### ISSUE THREAD

**Issue by SpectatorNan** [caixw/apidoc#48]
文档看不到，不知如何使用
自己刚搭建环境
小弟不才， 没接触过go  
clone 下来之后 
报错有资源找不到
![image](https://user-images.githubusercontent.com/13959374/47413169-2c228880-d7a0-11e8-9cdb-d1e616b36904.png)

**Comment by caixw** [comment]
可执行文件现在在 cmd 目录下。需要在那里运行 go run 或是 go build。
go run 如果指定单一文件，则只编译运行该文件。最好还是 build 完再运行吧。

目前 master 是开发分支，最好用 tag 4.0 的，那个是稳定的。

**Comment by SpectatorNan** [comment]
tag 4.0
我这个报的是  package找不到  是不是要修改配置文件
![image](https://user-images.githubusercontent.com/13959374/47438355-e59f4f00-d7dc-11e8-8fa5-8d684a02d1b5.png)

**Comment by caixw** [comment]
go1.11 之前项目要放在 GOPATH 下的相应目录，如果还是差包的话，用 go get 可以下载。
