### ISSUE TITLE
https://apidoc.tools 网站 访问不了，可否给出详细的使用用例呢？

### ISSUE THREAD

**Issue by bingochen87** [caixw/apidoc#49]
https://apidoc.tools 网站 访问不了，可否给出详细的使用用例呢？

**Comment by caixw** [comment]
额，目前网站改版中。估计要下周才能好。

**Comment by bingochen87** [comment]
那是否可以说一下是怎么用的，go-swagger实在是不好用，限制得太死板了。还是apidoc好用，也不知道你这个是不是跟apidocjs那个一样的。
写php的时候就是用的apidocjs, 非常好用。
谢谢了。

**Comment by caixw** [comment]
你 checkout tag 4.0，目录下有 docs 文件夹，那里保存的是 4.0 版本的文档。都是静态 HTML，直接用浏览器打开就可以用了。
