### ISSUE TITLE
找不到结束符号

### ISSUE THREAD

**Issue by SpectatorNan** [caixw/apidoc#50]
![image](https://user-images.githubusercontent.com/13959374/47710467-ca659100-dc6d-11e8-87ed-7e6be3516b17.png)
参数我是按照文档来的
文档分别在多个文件当中
![image](https://user-images.githubusercontent.com/13959374/47710456-c46fb000-dc6d-11e8-8afc-31582eef63cb.png)

**Comment by caixw** [comment]
方便贴一下整个文件的代码吗？

**Comment by SpectatorNan** [comment]
![image](https://user-images.githubusercontent.com/13959374/47760806-1d345c80-dcf1-11e8-9418-459957f4720e.png)

**Comment by caixw** [comment]
奇怪，我这边测试 4.0 和 master 分支的都没有问题。确定编码是 utf-8 吗？

**Comment by SpectatorNan** [comment]
恩  Swift  都是utf-8

**Comment by SpectatorNan** [comment]
https://github.com/SpectatorNanWithZZC/creditCaculatorVapor/tree/dev/Sources/App/Routers

这个是我写路由的目录地址

**Comment by caixw** [comment]
@SpectatorNan 奇怪，这个目录下的内容，我这里依然是可以正常生成文档的。
