### ISSUE TITLE
能否支持json格式呢？

### ISSUE THREAD

**Issue by godcong** [caixw/apidoc#53]
好像没看到json配置文件的支持。
原来用的apidocjs是支持的，后来转成这个。
但配置还是用json写的。。。

希望toml，yaml，json都能支持

**Comment by godcong** [comment]
no response

**Comment by caixw** [comment]
不好意思，年底忙，不怎么处理邮件。

主要是感觉 ymal 阅读性更好一点，所以改成了 yaml。等这个版本的主要功能完成之后，可能会加回对其它格式配置文件的支持吧。
