### ISSUE TITLE
为什么非得xml, ini不香吗, toml不香吗, json不香吗, yaml不香吗, 随便哪个都比xml好吧

### ISSUE THREAD

**Issue by zlyuancn** [caixw/apidoc#55]
为什么非得xml, ini不香吗, toml不香吗, json不香吗, yaml不香吗, 随便哪个都比xml好吧

**Comment by caixw** [comment]
JSON 和 INI 对于富文本并不合适，虽然 apidoc 基本上用不到富文本，但是提供了该功能；
YAML 嵌在大段的注释中，很容易出现缩进不统一的情况；
INI、TOML、JSON 和 YAML 并没有属性的概念，每一个值必须得一行，会造成注释代码过于冗长；

而且部分代码风格会限制每一行的长度，JSON 和 YAML 在嵌套比较深的情况下，每一行写不了几个字。而在不缩时的情况下，XML 的可读性是最好的。
