### ISSUE TITLE
提供demo頁面

### ISSUE THREAD

**Issue by davix** [caixw/apidoc#57]
想看看生成後的頁面是什麼樣

**Comment by caixw** [comment]
官网下有的: <https://apidoc.tools/example/index.xml>

**Comment by davix** [comment]
好，不過在readme和官網顯著位置沒提到。

**Comment by caixw** [comment]
官网里在 《https://apidoc.tools/#spec> 这一节有提到，README.md 里没有。

目前在文档维护这一块做的比较差，如果你有好的建议可以 PR 过来。
