### ISSUE TITLE
如何使 apidoc  是支持 二方依赖包裹的 接口描述  配置 ？

### ISSUE THREAD

**Issue by Seriels** [caixw/apidoc#58]
我们想将 新项目从 swagger 转换成 api doc  但是 发现某些模块是 由其他人人员 开发的 jar 形式  依赖包   引入进来的

**Comment by caixw** [comment]
swagger 和 apidoc 并不兼容。引入进来的依赖包，应该不存在需要 apidoc 解析的内容。
所以你在自己的项目中另一个文件里把需要的文档写上就行了。

**Comment by Seriels** [comment]
好的 了解情况了
