### ISSUE TITLE
panic: template: html:1: unexpected "-" in define clause

### ISSUE THREAD

**Issue by RamboLau** [caixw/apidoc#7]
通过go build编译的报错。

panic: template: html:1: unexpected "-" in define clause

goroutine 1 [running]:
html/template.Must(0x0, 0x52d028, 0xc82026a140, 0x0)
        /usr/local/go/src/html/template/template.go:330 +0x4b
github.com/caixw/apidoc/output.compileHTMLTemplate(0xc820010c40, 0x296f5, 0x0, 0x0)
        /Users/xxxx/gocode/src/github.com/caixw/apidoc/output/html.go:88 +0x6cd
github.com/caixw/apidoc/output.renderHTML(0xc8201f16d0, 0xc820010c40, 0x0, 0x0)
        /Users/xxxx/gocode/src/github.com/caixw/apidoc/output/html.go:41 +0x45
github.com/caixw/apidoc/output.Render(0xc8201f16d0, 0xc820010c40, 0x0, 0x0)
        /Users/xxxx/gocode/src/github.com/caixw/apidoc/output/output.go:56 +0xab
main.main()
        /Users/xxxx/gocode/src/github.com/caixw/apidoc/main.go:50 +0x194

**Comment by caixw** [comment]
这个 go 的版本问题，1.6及之后没有问题。之前的话如果要编译通过，得模板中的 - 去掉。
